mysql:
  innodb_buffer_pool_size: 1024M
  innodb_log_file_size: 256M
  innodb_log_buffer_size: 128M
galera:
  cluster_name: galera_bench
  gcache_size: 128M
  wsrep_cluster_address: "{{ wsrep_address }}"
  wsrep_node_name: "{{ wsrep_node_name }}"
  wsrep_node_incoming_address: "{{ wsrep_address }}"
  wsrep_slave_threads: 3
  wsrep_retry_autocommit: 0

  pip_packages:
  - MySQL-python
  - pycrypto

  pre_apt_packages:
  - python-software-properties
  - software-properties-common
  - debconf-utils

  debconf_items:
  - question: "mysql-server/root_password"
    name: "{{   mariadb_server_package }}"
    value: "{{   root_password }}"
    vtype: "string"
  - question: "mysql-server/root_password_again"
    name: "{{   mariadb_server_package }}"
    value: "{{   root_password }}"
    vtype: "string"
