mysql:
  innodb_buffer_pool_size: 1024M
  innodb_log_file_size: 256M
  innodb_log_buffer_size: 128M
galera:
  cluster_name: galera_bench
  gcache_size: 128M
  wsrep_cluster_address: "{{ wsrep_address }}"
  wsrep_node_name: "{{ wsrep_node_name }}"
  wsrep_node_incoming_address: "{{ wsrep_address }}"
  wsrep_slave_threads: 3
  wsrep_retry_autocommit: 0

  pip_packages:
  - MySQL-python
  - pycrypto

  pre_apt_packages:
  - python-software-properties
  - software-properties-common
  - debconf-utils

# The package name for mariaDB is set as a variable
# so that it can be used in debconf later in the
# "  common" role.
  mariadb_server_package: "mariadb-galera-server-5.5"

# NB This is specifically   packages as these packages only get installed
# during the galera play - this is because of the preseed task and the service
# startup control used when installing mariadb-galera-server and galera.
  apt_packages:
  - mariadb-client
  - "{{   mariadb_server_package }}"
  - galera
  - rsync
  - xtrabackup
  - socat

  debconf_items:
  - question: "mysql-server/root_password"
    name: "{{   mariadb_server_package }}"
    value: "{{   root_password }}"
    vtype: "string"
  - question: "mysql-server/root_password_again"
    name: "{{   mariadb_server_package }}"
    value: "{{   root_password }}"
    vtype: "string"
